# =========================
# Runtime image
# =========================

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base

WORKDIR /app

EXPOSE 8080



# =========================
# Build image
# =========================

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build

WORKDIR /src


# Copy source code
COPY . .


# Restore packages
RUN dotnet restore


# Publish application
RUN dotnet publish Stackoverflow.Host/Stackoverflow.Host.csproj \
    -c Release \
    -o /app/publish



# =========================
# Final image
# =========================

FROM base AS final

WORKDIR /app


COPY --from=build /app/publish .


ENTRYPOINT ["dotnet", "Stackoverflow.Host.dll"]